"""empty message

Revision ID: d0f7e61053a9
Revises: 93dda60cc14b
Create Date: 2025-04-04 18:40:16.107926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f7e61053a9'
down_revision = '93dda60cc14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_author', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
